puppetlabs/puppetlabs-vcsrepo

- spec/unit/puppet/provider/vcsrepo/git_spec.rb
removing private tests, due to rspec3 not handling private methods
> removing private tests

- spec/acceptance/clone_repo_spec.rb
Since lets can't be used in before :all any more.
> Update let to use instance variable instead.

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
This PR adds the ability to skip initializing git submodules when cloning a repository (i.e. `git submodule update --init --recursive`)
The default behaviour is still the same.
> Add submodules feature to git provider

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- spec/acceptance/modules_753_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
This PR allows multiple remotes to be used by specifying a hash of name => URL mappings in the source property, instead of just a single URL string.
> Implemented multiple remotes feature for git provider.

- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Without this commit, the unit tests for the git provider changing
multiple remotes mocks the remotes in a particular order. While in
practice it doesn't matter which remote the update_remotes method
updates first, the unit tests must be able to mock them in the correct
order. For ruby 1.8.7, a Hash will not necessarily produce key value
pairs in the same order on each run, which causes intermittent failures
in the unit tests. This change sorts the :source property values before
trying to update them, and updates the unit tests to expect the values
in alphabetical order.
> Fix remote hash ordering for unit tests

- lib/puppet/provider/vcsrepo/svn.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Allow setting the subversion behaviour on encountering conflicts to something other than the default (postpone), which is undesirable in many cases.
https://tickets.puppetlabs.com/browse/MODULES-1551
> Add support for 'conflict' parameter to populate svn --accept arg

- README.markdown
Replace all double quotes with single quotes (no quoted variables or single quotes).
Fix an open quote on line 338 and incorrectly quoted parameter names on lines 164-165.
> Enforce the style guide's recommendation of single quotes as the default.

- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
I try to clone a single revision from arbitrary branch. Something like:
git clone --depth 1 --branch v2.6.1 https://github.com/symfony/symfony-standard.git
Here: v2.6.1 is a tag. And I want to clone only one revision: the one that corresponds to this tag.
The following configuration:
vcsrepo { '/home/vagrant/p01':
provider => 'git',
source   => 'https://github.com/symfony/symfony-standard.git',
user     => 'vagrant',
revision => 'v2.6.1',
depth    => 1
}
fails producing the error:
Error: Execution of '/bin/su vagrant -c git checkout --force v2.6.1' returned 1:
error: pathspec 'v2.6.1' did not    match any file(s) known to git.
I think `branch` parameter is necessary.
I have already made one PR: #212
This time I removed superfluous parameter `--single-branch`.
What do you think @sodabrew?
> Shallow clone with one commit that corresponds to arbitrary tag from arbitrary branch

- examples/p4/create_client.pp
- examples/p4/delete_client.pp
- examples/p4/latest_client.pp
- examples/p4/sync_client.pp
There were puppet lint warnings due to indentation in several examples.
This commit cleans up the warnings.
Signed-off-by: Andrew Grimberg <agrimberg@linuxfoundation.org>
> Clean up puppet lint warnings

- lib/puppet/provider/vcsrepo/git.rb
Very often /tmp is mounted noexec for security reasons related to it
being writable by all users. This stopped vcsrepo's git provider from
working.
This pull request uses puppet's statedir as it is not writable by all
users and is a good candidate for transient state like the git
provider's identity script for the $GIT_SSH command.
An alternative in the future that wouldn't require a temporary file is
to set $GIT_SSH_COMMAND instead of $GIT_SSH, except this was added in
git 2.3 and is too new to depend on.
> (MODULES-821) Don't use /tmp

- lib/puppet/provider/vcsrepo/git.rb
This fixes the problem when cloning a specific revision of a repository that does not have any submodules, the following error was showing up:
git submodule update --init --recursive                
No submodule mapping found in .gitmodules for path
Now after this bugfix and explicitly specifying the submodules parameters to false, the error is gone.
> Consider the submodules flag on specific revision cloning

- spec/acceptance/clone_repo_spec.rb
In MODULES-891 the question arose whether https sources are supported.
This test shows that it works.
> acceptance: Add a test verifying anonymous https cloning

- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
MODULES-2131 Git provider now takes account of revision property when using depth property.
> MODULES-2131 Git provider now takes account of revision property when using depth property.

- lib/puppet/provider/vcsrepo/git.rb
- spec/acceptance/modules_1800_spec.rb
This would explode when revision was unspecified when you were on a
branch. Use the branch you're currently on when updating.
> MODULES-1800 - fix case where ensure => latest and no revision specified

- spec/acceptance/modules_2326_spec.rb
The ssh-keygen is waiting for a 'y' to confirm overwrite, and the test hangs.
> Fix acceptance hang

- lib/puppet/provider/vcsrepo/git.rb
Even if the -i flag is explicitly passed via the command line, openssh
ignores the identity file if an socket exists to an SSH authentication
agent.  In cases where puppet has been configured to use an explicit
identity file, altering behavior based on the calling environment of
puppet violates the principle of least surprise, and can lead to
inconsistent deployments.
Work around this odd corner case of ssh by explicitly unsetting
SSH_AUTH_SOCK inside the ssh wrapper.
> Explitly unset SSH_AUTH_SOCK; it is preferred to the -i flag

- lib/puppet/type/vcsrepo.rb
Along the lines of 2b190756260346931b8f9a0dda8afc0c815710d6, if the
Mercurial package is being managed, it stands to reason that the Mercurial
package should be installed before trying to potentially manage Mercurial
repositories using vcsrepo resources.
This commit adds an autorequire to the vcsrepo type that reflects the
above premise.
> Autorequire Package['mercurial']

- lib/puppet/provider/vcsrepo/git.rb
this will stop failing in case there is a tag which is a substring of an existing branch name.
for example if there is a tag 'release' and a branch 'release/integration' current code will match 'release/integration' with pattern 'release' and decide that a branch checkout is needed. but release branch does not exist so it will fail.
this simple fix resolves the issue.
> fix branch existence determintaion functionality

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Example:
```
vcsrepo { '/path/to/repo':
ensure   => mirror,
provider => git,
source   => 'git://example.com/repo.git',
}
```
> Add mirror option for git cloning

- lib/puppet/provider/vcsrepo/cvs.rb
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/provider/vcsrepo/hg.rb
- spec/unit/puppet/provider/vcsrepo/cvs_spec.rb
Up for discussion, this change is only for git, hg and cvs right now.
I wanted to see the stderr output, and :combine will write it to stdout, so its visible in the Puppet report
> Bring stderr output to the Puppet visible output

- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/type/vcsrepo_spec.rb
The insync? method wasn't accounting for a condition where the state was
absent and the desired state was absent. This manifest itself in puppet
runs that would constantly output the following after setting
ensure => absent.
2016-09-01T16:39:27.314283+00:00 vcstest puppet-agent[1161]: (/Stage[main]/Main/Node[vcstest]/Vcsrepo[/home/vagrant/test]/ensure) created
2016-09-01T16:40:22.583125+00:00 vcstest puppet-agent[1727]: (/Stage[main]/Main/Node[vcstest]/Vcsrepo[/home/vagrant/test]/ensure) created
2016-09-01T16:41:04.031750+00:00 vcstest puppet-agent[2267]: (/Stage[main]/Main/Node[vcstest]/Vcsrepo[/home/vagrant/test]/ensure) created
2016-09-01T16:42:51.779816+00:00 vcstest puppet-agent[2911]: (/Stage[main]/Main/Node[vcstest]/Vcsrepo[/home/vagrant/test]/ensure) created …
> Fix bug in ensure => absent

- CHANGELOG.md
- README.markdown
-   Added missing Debian 8 and Ubuntu 16.04 platforms to the readme.
-   Standardized/reverted line ending characters throughout the readme.
-   Added `puppet` syntax highlighting to code blocks.
-   Aligned hash rocket in Puppet code blocks.
-   Standardized spacing between heading Markdown and text.
-   Standardized sentence case on headings.
-   Updated section targets in Perforce docs links.
-   Fixed a broken link to the Mercurial docs.
-   Updated puppetlabs.com URLs to puppet.com.
-   Updated Puppet Labs references to Puppet Inc.
-   Updated a Projects wiki link to the docs site.
-   Added dates to the 1.4.0 and 1.3.2 releases on the changelog.
> (FM-5559) Readme and changelog edits for signoff

- lib/puppet/provider/vcsrepo.rb
- lib/puppet/provider/vcsrepo/bzr.rb
- lib/puppet/provider/vcsrepo/cvs.rb
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/provider/vcsrepo/hg.rb
- lib/puppet/provider/vcsrepo/p4.rb
- lib/puppet/provider/vcsrepo/svn.rb
- lib/puppet/type/vcsrepo.rb
- spec/acceptance/clone_repo_spec.rb
- spec/acceptance/modules_1800_spec.rb
- spec/unit/puppet/provider/vcsrepo/bzr_spec.rb
- spec/unit/puppet/provider/vcsrepo/cvs_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
- spec/unit/puppet/provider/vcsrepo/hg_spec.rb
- spec/unit/puppet/provider/vcsrepo/p4_spec.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
- spec/unit/puppet/type/vcsrepo_spec.rb
Changes common to all providers:
- `:source` is now a property
- `check_force` moved from git provider to base vcsrepo provider
- `check_force` added to every provider's create method
- use provider binary for `exists?` (not just directory check*)
Changes to specific providers:
- bzr
- `source` returns the `parent branch` as output by `bzr info`
- changing `:source` calls `provider.create`
- cvs
- (*) init'd repos make `cvs status` error, so it still relies on
file/directory checks. That is, from what I can tell.
- module properly handles checkout paths now
- `source` returns the contents of file `<path>/CVS/Root`
- changing `:source` calls `provider.create`
- `:module` is now a property
- `module` returns the contents of file `<path>/CVS/Repository`
- changing `:module` calls …
> Make :source a property, + some refactoring

- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/acceptance/clone_repo_spec.rb
- spec/acceptance/create_repo_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Currently the git provider handles changes between :bare/:mirror and
:present/:latest inside its checkout and init calls. That's a bit silly,
so I moved the logic inside the ensurable block. Now when you change the
ensure type it will show the proper "ensure changed" notice.
This meant I had to pull the conversion functions up from the private
section of the methods to the public.
I also fixed up some of the code to be more robust. It now sets mirror
properties and all that.
> "Better" handling of :ensure changes

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/provider/vcsrepo/svn.rb
- lib/puppet/type/vcsrepo.rb
- spec/acceptance/svn_paths_spec.rb
- spec/acceptance/svn_spec.rb
- spec/spec_helper_acceptance.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
I extended the SVN provider to include some particular functionality I needed, but I'm not sure if it fits with the "goal" of the module. If it does, I'll add tests and make it more robust; otherwise I'll fork it off into my own module.
Two features have been added to the provider.
1. Export support
Added `:export` parameter/feature to type/provider -- accepts `:true` or `:false`
Provider runs `svn export` instead of `svn checkout` if `:export` is `true`, which creates an non-versioned copy of the working tree in `path`. Of course, since it is non-versioned, there is no way of tracking revision through `svn`, so each subsequent puppet run requires `:force` to be `true`.
2. Cherry-picking individual files from the repo
Added `:files` parameter/feature to type/provider -- accepts array …
> Adding svn provider support for versioning of individual files

- README.markdown
- lib/facter/vcsrepo_svn_ver.rb
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/provider/vcsrepo/svn.rb
- spec/acceptance/svn_paths_spec.rb
- spec/acceptance/svn_spec.rb
- spec/unit/facter/vcsrepo_svn_ver_spec.rb
Fix to git provider on older git versions where git config --local param not supported. Update SVN provider to remove Includes option support from SVN versions < 1.7 and update tests and README to reflect this.
These issues were picked up on RHEL6 based distros as they use older versions of git and svn.
> [MODULES-3998] Fix to GIT and SVN providers to support older versions of git and svn

- README.markdown
- lib/puppet/provider/vcsrepo/bzr.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/cvs_spec.rb
- spec/unit/puppet/type/vcsrepo_spec.rb
I don't know why I didn't realize that `insync?` was the smarter way to
get around `/` munging by providers. But I did, so there.
Also, it now errors when an include path starts with a `/`.
Removing @wilson208's "without trailing slash" from README since it's
no longer needed.
> Better management of '/'s for :source and :includes

- README.markdown
- lib/puppet/provider/vcsrepo/svn.rb
- spec/acceptance/svn_paths_spec.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
- Handle sparse directory path updates recursively
- Always try to get around svn 1.6 sucking at sparse directories
- Throw a warning when impossible
- Raise error when using `:includes` and svn < 1.6
- Updates to README
> Make :includes work with svn 1.6

- lib/puppet/provider/vcsrepo/dummy.rb
Deployed vcsrepo on a windows 2012R2 server.  It was throwing a warning.  This cleans it up.
> Fix muliple default provider warning on windows

- spec/acceptance/svn_paths_spec.rb
The regex changed was ensuring the test within the if block only run on debian and ubuntu versions with SVN 1.6. However, the regex for debian 6 was matching on 16.04 also when it was not meant to.
> [MODULES-4139] Fix CI failures in CI on ubuntu 16.04 caused by regex matching on 16.04 when it is not meant to.

- README.markdown
Adds an example for using a non-standard SSH port by specifying the full
SSH scheme.
> (MODULES-1910) document non-standard SSH port

- lib/puppet/provider/vcsrepo/svn.rb
As by https://tickets.puppetlabs.com/browse/MODULES-4280
The svn provider is now broken.
Introduced by https://github.com/puppetlabs/puppetlabs-vcsrepo/commit/d26905fde50c4b8ce47dc0da7232028dc914a327#diff-574463866055cc3f49ee013638f6652aL80
PR not well tested.
> Fix to get svn provider working again

- spec/unit/puppet/provider/vcsrepo/git_spec.rb
It is not possible for the test to ever pass due to the logic in the
create/check_force. Removing this test rather than keeping it in the
code base commented out.
> (MODULES-5162) - Removing commented out test

- lib/puppet/provider/vcsrepo/svn.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Change method 'working_copy_exists' to use 'svn info' instead of 'svn status'. 'svn status' does not return proper exit codes, while 'svn info' does.
Fixes https://tickets.puppetlabs.com/browse/MODULES-5615
> [MODULES-5615] Fix for working_copy_exists

- lib/puppet/provider/vcsrepo/cvs.rb
- spec/unit/puppet/provider/vcsrepo/cvs_spec.rb
The working copy detection for cvs if the source parameter is present fails
because the cvs -d option is only to specify the root repository and not the
working copy.
> (MODULES-5704) Fix cvs working copy detection

- CHANGELOG.md
great job by @david22swan, just made some minor changes that may or may not be documented:
- updated entries that have an associated JIRA ticket to include a link to that ticket
- rearranged a few entries under new headings, 'Changed' should only be used for backwards-incomaptible changes
- removed date from release heading and added a link at the bottom of the page for 2.1.0
- added language around dropping support for platforms. we've had some churn about 'removing support' in the past and it's important to include a note about compatibility.
- changed language for some entries. we try to treat each heading as the
beginning of a sentence, e.g. each entry under 'Fixed' should be a
continuation of a sentence that starts with the word 'Fixed...'
> updates to changelog for 2.1.0 release

- lib/puppet/provider/vcsrepo/svn.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Throw an error with a descriptive error message when only one of the required
properties for enabling HTTP Basic auth is specified, as the user's true
intent isn't clear from such input. This contrasts with the previous behavior,
in which HTTP Basic auth was silently disabled.
> Do not ignore incorrect HTTP Basic auth property specifications.

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
closes #359 
- Added trust_server_cert support to Git provider
- Checking for Git version now, the -c parameter wasn't always available
- Moved the trust_server_cert part to git_with_identity, so it works for cloning, fetching, etc.
- Updated the README.
- Changed vcsrepo_git_ver regex to use %r{...}
- Using git('--version') now, removed Git version fact.
> (MODULES-5889) Added trust_server_cert support to Git provider

- lib/facter/vcsrepo_svn_ver.rb
On macOS ("Darwin"), check that the xcode-select path exists before attempting to run svn.  This avoids the popup dialog that is produced when the developer tools are not yet installed.
> Avoid popup on macOS when developer tools aren't installed

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
This PR raises an error when the source is not specified when `ensure=>latest` using the git provider. Prior to this PR, the resource would create a bare repository and fail when checking the branches with a generic `nil:Nilclass` error.
> (FM-6697) Add error when a source is not specified with latest

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Reverts puppetlabs/puppetlabs-vcsrepo#371
This change caused test failures on the associated unit test
> Revert "(FM-6697) Add error when a source is not specified with latest"

- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
When using a SHA revision, a `git fetch` does not need to be done if the current HEAD is already pointing to the requested SHA.
> Improve Git performance when using SHA revisions

- NOTICE
The change in https://github.com/puppetlabs/puppetlabs-vcsrepo/commit/a41f7fcae6bbe7a68fab12623c1ba0642cf5f226 was an oversight that was created using modulesync. This PR puts the NOTICE back to how it should be and aligns with the LICENSE file and the metdata.json entry.
This module remains as licensed under: GNU General Public License
> (maint) - Fix NOTICE for license

- lib/puppet/provider/vcsrepo/svn.rb
Use a clearer error message for the case where the existing local repository was created by a more recent SVN version than the one currently in use.
> Use clearer error message for "This client is too old to work with the working copy"

- README.markdown
- lib/puppet/provider/vcsrepo/hg.rb
- lib/puppet/provider/vcsrepo/svn.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/hg_spec.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
The parameter basic_auth_password does not support Sensitive values. As such, passwords are logged in plain text. This change rectifies this by allowing the user to specify either a standard string or Sensitive value.
> (MODULES-8738) Allow Sensitive value for basic_auth_password

- README.markdown
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Add an option to keep local changes when revision changes.
As we do a `git checkout --force` all local modifications are removed.
We just add an option that stash the modification before the checkout and
unstash the modification after the checkout.
This change is backward compatible, as by default, we keep the current
behaviour and do not keep local modification.
> feature(git): add keep local changes option

- metadata.json
- spec/acceptance/clone_repo_spec.rb
Add support on Debian10
pdk version: `1.12.0` 
added extra 10 seconds because the process was still running and test user couldn't be deleted
> pdksync - Add support on Debian10

- lib/puppet/provider/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
When using puppetlabs-vcsrepo with the owner parameter (or
with the group parameter), the entire git repository is chowned
recursively on every update.
This chown can be very long if there are a lot of files in the
repository destination path. This commit excludes the files defined in
the `excludes` parameter in the chown.
refs https://tickets.puppetlabs.com/browse/MODULES-5922
> feat: do not chown excluded files

- lib/puppet/provider/vcsrepo/git.rb
Per: "man git", GIT_SSH_COMMAND will take precedence over GIT_SSH. Thus,
if GIT_SSH_COMMAND is set and leaks into the environment, then this
module's use of the GIT_SSH environment variable will not work.
Unset GIT_SSH_COMMAND for the environment in which the git command
execs.
> Unset GIT_SSH_COMMAND before exec'ing git command

- lib/puppet/provider/vcsrepo/git.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
If the git config `color.ui` is set to "always", then you get ANSI escape codes in the git output, which messes up comparisons, and results in errors on puppet agent runs. This pull request prevents color in the output.
> prevent ANSI color escape sequences from messing up git output

- CHANGELOG.md
- metadata.json
Successful on 21 nodes: ["conceptual-deck.delivery.puppetlabs.net, sles-12-x86_64", "haughty-lookout.delivery.puppetlabs.net, ubuntu-1404-x86_64", "annual-banter.delivery.puppetlabs.net, sles-15-x86_64", "vigilant-maid.delivery.puppetlabs.net, redhat-6-x86_64", "fatal-tailor.delivery.puppetlabs.net, debian-8-x86_64", "foamy-least.delivery.puppetlabs.net, scientific-7-x86_64", "visual-luxury.delivery.puppetlabs.net, oracle-7-x86_64", "pretend-assault.delivery.puppetlabs.net, scientific-6-x86_64", "remote-legato.delivery.puppetlabs.net, centos-6-x86_64", "indirect-eva.delivery.puppetlabs.net, ubuntu-1604-x86_64", "concerted-while.delivery.puppetlabs.net, oracle-6-x86_64", "anomic-equine.delivery.puppetlabs.net, redhat-8-x86_64", "rougher-jest.delivery.puppetlabs.net, debian-9-x86_64", …
> Release prep version 3.1.1

- spec/acceptance/clone_repo_spec.rb
With the default branch on github for the vcsrepo module being updated
from 'master' to 'main' when the module clones the default HEAD is now
'main' rather than 'master'.
> (IAC-1223) Correct clone https test

- lib/puppet/provider/vcsrepo/svn.rb
- spec/acceptance/svn_spec.rb
- spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Removing unwrap. When it is called, unwrap is a puppet method, therefore not available in Ruby and throws an error. Also the value is unwrapped earlier, therefore it is pretty much trying to unwrap the value twice. 
Adding an acceptance test to confirm the Sensitive value works.
The following PR is adding the same test as added here, and all acceptance tests are failing which proves this fix is needed.
https://github.com/puppetlabs/puppetlabs-vcsrepo/pull/492
> (MODULES-9997) - Removing extra unwrap on Sensitive value

- lib/puppet/provider/vcsrepo/git.rb
- spec/acceptance/clone_repo_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Previously, if the resource specified `user`, then git would be executed as that user... except if you also provided `identity` to control which SSH key to use, in which case the code did the setup required for the git helper script, then called git directly (bypassing the bit that ran it as the desired user).
This changes it by wrapping up the execution of git in a new method which contains the logic to run as the specified user if they asked for that, and uses that wrapper from both places in git_with_identity.
> Always run as given user, even if identity set

- lib/puppet/provider/vcsrepo/git.rb
On Git revisions 2.20.0 in order to force sync remote tags with local
ones, the parameter --force has to be passed or an error will be
raised.
On previous versions the --force behaviour was the default
> MODULES-11050 - Force fetch tags

- README.md
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/acceptance/clone_repo_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
After git was patched for [CVE-2022-24765](https://nvd.nist.gov/vuln/detail/CVE-2022-24765) the git binary would fail to execute in a repository that was owned by another user or group.
As of git 2.35.2, you can specify the `safe.directory` configuration or for prior versions define the `GIT_CEILING_DIRECTORIES` environment variable to whitelist known directories.
For users of VCSRepo running newer  of git, there was no obvious way to apply the remediation.
This PR will close #535 by adding a `safe_directory` property to the type, allowing users to explicitly mark a path as 'safe'.
> (GH-535) Fix for safe directories

- lib/puppet/provider/vcsrepo/git.rb
Prior to this PR the module would fail when executed under the context of systemd.
This was because Dir.home tries to expand `~` when no UID is passed.
However the HOME environment variable is not available when the agent is executed by systemd resulting in the following error:
`Could not evaluate: couldn't find login name -- expanding ~`
This commit fixes this by reverting to using Etc.getpwuid so that we can retrieve the home dir from the  uid of the current process.
For consistency, retrieval of home dirs for a given user has also been changed to use Etc.getpwnam.
Fixes #552
> (GH-552) Fix home directory evaluation

- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/acceptance/clone_repo_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Add new property `skip_hooks` to control wether the repository should actively ignore configured hooks(local, global or system)
Implemented for the `git` provider
When using `vcsrepo` to manage a git repository, having global git hooks configured can mess with the functionality of the module. If checkout hooks are configured they may make any git checkout operation fail.
> Add skip_hooks property to vcsrepo 

- README.md
- lib/puppet/provider/vcsrepo.rb
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/acceptance/clone_repo_spec.rb
This is a re-attempt of: https://github.com/puppetlabs/puppetlabs-vcsrepo/pull/541
I can't re-open that PR (see: https://github.com/puppetlabs/puppetlabs-vcsrepo/pull/541#issuecomment-1281991334).
@jordanbreen28 can you please either check this one or re-open the original PR, if possible now?
Differences from the last revision of the original PR are:
* rebased
* fixed integration test
Thanks,
Corey
> support umask for git repos (try 2)

- spec/acceptance/clone_repo_spec.rb
When `pdk bundle exec rake litmus:acceptance:parallel` is run twice, the second command hangs. This happens because ssh-keygen is waiting for interactive input:
```
/home/testuser-ssh/.ssh/id_rsa already exists.
Overwrite (y/n)?
```
To fix this, ensure that we start out with an empty .ssh directory each time.
> fix repeated acceptance tests on the same container

- README.md
- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Proxies can be specified either as a single proxy or as one or more per-remote proxies.
Since the proxy config need not be supported for _every_ git command, define a new wrapper function to be used for git operations that need remote access, and then prepend the proxy arguments in that wrapper.
This implementation is better than the previously-documented method of using proxies when:
a. Global configuration is not desired.
b. Initial `git clone` should/must use a proxy.
The previously-documented method is still available for different use cases; reword the original instructions so that they are specified as an alternative rather than the primary method.
Move all proxy information into its own section, since this has become rather large to be included in general git usage.
> support per-repo HTTP proxy for the git provider

- lib/puppet/provider/vcsrepo/git.rb
Older versions (<2.3) do not support GIT_SSH_COMMAND yet. Fall back to GIT_SSH with a wrapper script.
Fixes [MODULES-11111](https://tickets.puppetlabs.com/browse/MODULES-11111)
> vcsrepo : identity doesn't work on EL7
> Bring back GIT_SSH support for old git versions

- README.md
- lib/puppet/provider/vcsrepo/git.rb
- spec/acceptance/clone_repo_spec.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
Due to  mistake in the logic unsafe directory was previously removed on every other run. The logic previously checked whether the unsafe directory needed to be added, removing it if this was false without taking into account when it was already set but we wanted it to be left in place.
In addition: safe directory is now set at a system wide level rather than at a global user level in order to ensure it is as effective as possible.
> (GH-585/CONT-998) Fix for safe_directory logic

- lib/puppet/provider/vcsrepo/git.rb
- lib/puppet/type/vcsrepo.rb
- spec/unit/puppet/provider/vcsrepo/git_spec.rb
On systems with a git version too old to support the `GIT_SSH_COMMAND`, a git wrapper script is created in the default temp directory. If that filesystem is mounted `noexec`, git is unable to execute the wrapper script:
```
Error: Execution of 'git clone git@github.com:org/repo.git /repo_dir' returned 128: Cloning into '/repo_dir'...
fatal: cannot exec '/tmp/git-helper20230607-525-1fvzyp1': Permission denied
````
This was solved in https://github.com/puppetlabs/puppetlabs-vcsrepo/commit/7f97a76f4682a7c1d5bfbbc3cd5a6dd9523b1d96 by using the Puppet `statedir` instead of the default temp directory, but this was later reverted in https://github.com/puppetlabs/puppetlabs-vcsrepo/commit/684200247c33e42f095f9478033b1d2a50bbbab0.
This PR enables specifying the directory used for the wrapper …
> Allow specifying tmpdir for git wrapper script

- spec/acceptance/svn_paths_spec.rb
- spec/spec_helper_acceptance_local.rb
With the removal of support for RHEL6 from our modules, work must be done to cleanup and remove any residual code.
This PR does the same for vcs repo module. More info can be found #573
> (CAT-1429) Removal of redhat/scientific/oraclelinux for vcs repo module

- spec/acceptance/clone_repo_spec.rb
POSIX does not define `-e` as a valid option for echo(1).  Rely on printf(1) instead.
This fix acceptance tests on Ubuntu ARM where echo(1) outputs `-e` causing an invalid configuration:
```
/home/testuser-ssh/.ssh/config: line 1: Bad configuration option: -e
```
> Fix acceptance test on Ubuntu ARM

- spec/acceptance/files/create_git_repo.sh
The nightly build is failing with the new version of Git because testrepo.git is not recognized as a safe directory. In this PR, we are addressing the issue by adding testrepo.git to the safe directory at the system level.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
> (CAT-2053) add testrepo.git to safe.directory
