puppetlabs/puppetlabs-vcsrepo

README.markdown
In reference to: https://tickets.puppetlabs.com/browse/MODULES-419
Updating the readme to be more concise. Similar assumptions have come up multiple times in our org.
=> Updating 'excludes' in readme to be more concise. 

lib/puppet/provider/vcsrepo/git.rb
https://tickets.puppetlabs.com/browse/MODULES-2174
=> fix for detached HEAD on git 2.4+

lib/puppet/provider/vcsrepo/git.rb, spec/acceptance/create_repo_spec.rb, spec/unit/puppet/provider/vcsrepo/git_spec.rb
Will also work with empty repositories.
=> MODULES-2125 - Allow revision to be passed without source

lib/puppet/provider/vcsrepo/git.rb, spec/acceptance/modules_2326_spec.rb
The URL can have special characters, making the regex match fail.
=> MODULES-2326 - Run Regexp.escape on the source URL

.sync.yml, .travis.yml, lib/puppet/provider/vcsrepo/git.rb
HOME is not available in provider commands or Puppet::Util::Execution::execute so make sure it's set so global git configs can be picked up.
=> MODULES-1232 Make sure HOME is set correctly

examples/git/shallow-clone-with-just-one-commit.pp
Here is an example that illustrates how to clone a single commit from a given branch.
=> Example how to create a shallow clone with just one commit

Gemfile, lib/puppet/provider/vcsrepo/svn.rb, lib/puppet/type/vcsrepo.rb, spec/unit/puppet/provider/vcsrepo/svn_spec.rb
false is not a valid value; only :false is.
=> Fix :false to be default value

lib/puppet/provider/vcsrepo/svn.rb
proposed fix for frozen string problem in svn spec tests
=> (MODULES-4174) duplicates svn version fact value

CHANGELOG.md, metadata.json
Update CHANGELOG and metadata for new version 1.5.0
=> release_prep

lib/puppet/provider/vcsrepo/git.rb
Fix  SSH_AUTH_SOCKET=: is not an identifier
=> Fix Solaris sh-ism

lib/puppet/provider/vcsrepo/git.rb, lib/puppet/type/vcsrepo.rb, spec/unit/puppet/provider/vcsrepo/git_spec.rb
=> fixing force parameter to be boolean

metadata.json
MODULES-4823 puppetlabs-vcsrepo: Update the version compatibility to >= 4.7.0 < 5.0.0
=> MODULES-4823 puppetlabs-vcsrepo: Update the version compatibility to >= 4.7.0 < 5.0.0

README.markdown
typo error for sshed-git-source
=> specify protocol line 206 for ssh

metadata.json
Removal of Debian 6 and SLES 10.
Addition of Debian 9.
=> Updates to metadata.json

CHANGELOG.md, metadata.json
=> mergeback for 2.1.0

README.markdown
The anchor tag helps fix broken links — If the header text changes (gets localized) the link will brake.
=> (maint) Add HTML anchor tag

.sync.yml, metadata.json
(maint) travis updates: bundler and slack
pdk version: `1.15.0`
=> pdksync - (maint) travis updates: bundler and slack

.sync.yml, .travis.yml, metadata.json, provision.yaml
(IAC-215) - Implement use_litmus:true
pdk version: `1.16.0`
=> pdksync - (IAC-215) - Implement use_litmus:true

.github/workflows/release.yml, .github/workflows/weekly.yml
Updating workflow to use spec task since  the unit testcases are failing after merging this PR 
https://github.com/puppetlabs/puppetlabs-vcsrepo/pull/450/files
=> (maint) fix failures on spec tests

lib/puppet/provider/vcsrepo/svn.rb, spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Related to ticket(MODULES-10659)
=> check if pass containes non-ASCII chars before provider is created

CHANGELOG.md, CONTRIBUTING.md, HISTORY.md, README.md, spec/acceptance/clone_repo_spec.rb, spec/acceptance/create_repo_spec.rb, spec/acceptance/files/create_git_repo.sh, spec/acceptance/revision_spec.rb, spec/fixtures/git_branch_a.txt, spec/fixtures/git_branch_feature_bar.txt, spec/fixtures/git_branch_none.txt, spec/unit/puppet/provider/vcsrepo/git_spec.rb
Removal of any inappropriate or offensive terminology from the codebase
=> (IAC-1016) - Removal of Inappropriate Terminology

.github/workflows/nightly.yml, .github/workflows/pr_test.yml, .rubocop.yml, .travis.yml, Rakefile, lib/puppet/type/vcsrepo.rb, metadata.json
Update gha templates
pdk version: `1.19.0.pre (47)`
=> pdksync - Update gha templates

.github/workflows/auto_release.yml, .github/workflows/nightly.yml, .github/workflows/pr_test.yml, metadata.json, spec/acceptance/clone_repo_spec.rb
(MAINT) PDK update for GHA workflows + Litmus updates
pdk version: `1.18.1`
=> pdksync - (MAINT) PDK update for GHA workflows + Litmus updates

.github/workflows/nightly.yml, .github/workflows/spec.yml, examples/git/shallow-clone-with-just-one-commit.pp, lib/facter/vcsrepo_svn_ver.rb, lib/puppet/provider/vcsrepo/bzr.rb, lib/puppet/provider/vcsrepo/git.rb, lib/puppet/provider/vcsrepo/hg.rb, metadata.json
(Maint) PDK Update
pdk version: `2.3.0`
=> pdksync - (Maint) PDK Update

spec/acceptance/clone_repo_spec.rb, spec/acceptance/create_repo_spec.rb, spec/acceptance/multiple_remotes_spec.rb, spec/acceptance/remove_repo_spec.rb, spec/acceptance/revision_spec.rb, spec/spec_helper_acceptance_local.rb
This PR fixes most acceptance test failures.
The remaining test failures are being caused by #535 and will be addressed in another PR.
Closes #540
=> (GH-540) Fix acceptance test failures

lib/puppet/provider/vcsrepo/git.rb
Fixes
https://github.com/puppetlabs/puppetlabs-vcsrepo/issues/565
=> Only remove safe_directory, if it exists

.devcontainer/devcontainer.json, .github/workflows/auto_release.yml, metadata.json
This PR reflects changes made by running "pdk update" - Includes:
1.  updating of metadata.json to the newest pdk version
2. modifies auto_release.yml to use the newest stable image of pdk for release 
3. a json formatting fix in devcontainer.json.
=> (maint) - PDK update

.github/release_prep.yml, .github/workflows/auto_release.yml
(CONT-930) - Roll out new changelog generator
pdk version: `2.7.1`
=> pdksync - (CONT-930) - Roll out new changelog generator

lib/facter/vcsrepo_svn_ver.rb, lib/puppet/provider/vcsrepo/dummy.rb, spec/unit/facter/vcsrepo_svn_ver_spec.rb
Update legacy facts with their respective counterparts.
=> (CAT-2228) Update legacy facts
